version: '2'

services:
  metabase:
    image: metabase/metabase
    ports:
      - 3333:3000
    volumes:
      - ./plugins/:/plugins

  de-sprint-6:
    image: cr.yandex/crp1r8pht0n0gl25aug1/de-sprint-6:latest
    ports:
      - 3000:3000
      - 3002:3002
      - 15432:5432
    volumes:
      - mydb:/var/lib/postgresql
      - mylessons:/lessons
      - ./dags:/lessons/dags

volumes:
  mydb:
  mylessons: